apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro
spec:
  selector:
    matchLabels:
      app: micro
  template:
    metadata:
      labels:
        app: micro
    spec:
      containers:
      - name: micro
        image: micro
        ports:
        - containerPort: 8080
kind: Service
apiVersion: v1
metadata:
  name: micro
spec:
  selector:
    app: micro
  ports:
  - port: 8080
    targetPort: 80

